docker compose override: 
version: "3.8"
name: real-time-container

services:
    mariadb-real-time:
        image: mariadb:10.6  # Versión estable
        container_name: mariadb-real-time
        environment:
            MYSQL_ROOT_PASSWORD: root_password       # Contraseña para el usuario root
            MYSQL_DATABASE: my_database              # Nombre de la base de datos
            MYSQL_USER: my_user                      # Nombre del usuario
            MYSQL_PASSWORD: my_password              # Contraseña del usuario
        ports:
            - "3306:3306"                            # Mapea el puerto 3306 (default de MariaDB)
        volumes:
            - mariadb_data:/var/lib/mysql            # Persistencia de datos
        networks:
            - sportboard-network

    ms3-real-time:
        build:
            context: ../../../backend/real-time  # Ruta relativa al código del proyecto Flask
            dockerfile: ../../docker/backend/ms3-real-time/Dockerfile  # Ruta relativa al Dockerfile
        container_name: ms3-real-time
        #restart: always
        environment:
            - FLASK_APP=/source/run.py
            - FLASK_ENV=development
            - DATABASE_URL=mysql+pymysql://my_user:my_password@mariadb-real-time:3306/my_database
        ports:
            - "5000:5000"
        depends_on:
            - mariadb-real-time
        volumes:
            - ../../../backend/real-time:/source  # Montar el código fuente en /source en el contenedor
            - static_volume:/app/staticfiles
        networks:
            - sportboard-network

volumes:
    mariadb_data:
    static_volume: