services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password123"
        ports:
            - "1433:1433"
    catalogs:
        container_name: catalogs
        build:
            context: ../../../backend/Catalogs
            dockerfile: ../../docker/backend/ms6-catalog/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CatalogDb;User=sa;Password=Password123;TrustServerCertificate=True
            - ASPNETCORE_URLS=http://localhost:5241
        ports:
            - "5241:5241"
        depends_on:
            - sqlserver