version: "3.8"
name: SportBoard-container

services:
    ms2-competencies:
        build:
            context: ../../../
            dockerfile: docker/backend/ms2-competencies/Dockerfile
        container_name: ms2-competencies
        restart: always
        environment:
            - DJANGO_SETTINGS_MODULE=competencies.settings
        ports:
            - "8003:8003"
        depends_on:
            - postgres



