services:
  # Aplicación principal
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - kong-net

  # Base de datos para Kong
  kong-database:
    image: postgres:15
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    volumes:
      - kong-db-data:/var/lib/postgresql/data
  kong-migrations:
    image: kong:3.5
    container_name: kong-migrations
    restart: "no"
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: kong migrations bootstrap
  # Kong Gateway
  kong:
    image: kong:3.5
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001,0.0.0.0:8444 ssl # puerto de administración
      KONG_ADMIN_GUI_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_GUI_URL: http://localhost:8002

    depends_on:
      - kong-database
    ports:
      - "8000:8000" # Puerto para las solicitudes proxy
      - "8443:8443"
      - "8001:8001" # Puerto para el administrador de Kong
      - "8002:8002"
      - "8444:8444"
    networks:
      - kong-net

networks:
  kong-net:

volumes:
    kong-db-data: