services:
  ms5-calendar:
    build:
      context: ../../../
      dockerfile: docker/backend/ms5-calendar/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - sportboard-network 

  calendar-migrations:
    image: kong:3.5
    container_name: calendar-migrations
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: kong migrations bootstrap
    networks:
      - sportboard-network 


networks:
  sportboard-network:
    external: true

volumes:
  kong-db-data: