version: "3.8"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  mobile:
    build:
      context: ../mobile
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
