name: SportBoard-container

services:
    postgres:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: postgres

    kong-migrations:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: kong-migrations

    kong:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: kong

# Microservicio de catálogo
    sqlserver:
        extends:
            file: ./backend/ms6-catalog/docker-compose.override.yml
            service: sqlserver
    
    catalogs:
        extends:
            file: ./backend/ms6-catalog/docker-compose.override.yml
            service: catalogs

networks:
    sportboard-network:
        name: sportboard-network
        driver: bridge
