version: "3.8"
name: SportBoard-container

services:
    postgres:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: postgres

    kong-migrations:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: kong-migrations

    kong:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: kong

networks:
    default:
        name: kong-network
