_format_version: "3.0"
_transform: true

services:
  - name: sportboard-backend
    url: http://ms4-estadisticas:3000
    routes:
      - name: teams-route
        paths:
          - /api/estadisticas/teams
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: matches-route
        paths:
          - /api/estadisticas/matches
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: competition-route
        paths:
          - /api/estadisticas/competition
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: upcoming-matches-route
        paths:
          - /api/estadisticas/upcomingMatches
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: leaderboards-route
        paths:
          - /api/estadisticas/leaderboards
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: players-route
        paths:
          - /api/estadisticas/players
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: generate-pdf-route
        paths:
          - /api/estadisticas/generate-teams-pdf
        strip_path: false
        methods:
          - POST
      - name: download-pdf-route
        paths:
          - /api/estadisticas/download-pdf
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: test-route
        paths:
          - /api/estadisticas/test
        strip_path: false
        methods:
          - GET
          - OPTIONS

consumers:
  - username: sportboard-consumer
    jwt_secrets:
      - key: sportboard-statistics
        secret: "1234"
        algorithm: HS256

plugins:
  - name: cors
    config:
      origins:
        - http://localhost:4200
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - Origin
        - X-Requested-With
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      preflight_continue: false

  - name: jwt
    config:
      claims_to_verify:
        - exp
      secret_is_base64: false
      run_on_preflight: true
      header_names: 
        - authorization